### ISSUE TITLE
TransactorIT failed

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#798]
Saw the following failure on TravisCI for #797  

```
Running org.apache.fluo.integration.impl.TransactorIT
2016-11-05 02:31:30,756 [imps.CuratorFrameworkImpl] ERROR: Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: Client is not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:113)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:477)
	at org.apache.curator.framework.imps.CreateBuilderImpl.performBackgroundOperation(CreateBuilderImpl.java:481)
	at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:65)
	at org.apache.curator.framework.imps.CreateBuilderImpl$10.callPerformBackgroundOperation(CreateBuilderImpl.java:659)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:802)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:490)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInBackground(CreateBuilderImpl.java:663)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:439)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.createNode(PersistentEphemeralNode.java:340)
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.access$000(PersistentEphemeralNode.java:53)
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode$1.process(PersistentEphemeralNode.java:70)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:61)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
2016-11-05 02:31:30,760 [imps.CuratorFrameworkImpl] ERROR: Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: Client is not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:113)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:806)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:490)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInBackground(CreateBuilderImpl.java:663)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:439)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.createNode(PersistentEphemeralNode.java:340)
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.access$000(PersistentEphemeralNode.java:53)
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode$1.process(PersistentEphemeralNode.java:70)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:61)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.025 sec <<< FAILURE! - in org.apache.fluo.integration.impl.TransactorIT
testTransactorAndCache(org.apache.fluo.integration.impl.TransactorIT)  Time elapsed: 3.865 sec  <<< FAILURE!
java.lang.AssertionError
	at org.apache.fluo.integration.impl.TransactorIT.testTransactorAndCache(TransactorIT.java:64)
```

**Comment by kpm1985** [comment]
@keith-turner I think you fixed this with the wonderful work you did lately getting the tests to  run correctly, no?

**Comment by keith-turner** [comment]
No that was another test that I fixed.  This test may still have problems.  Some test fail very infrequently.  Whenever I see a test fail I open an issue if one is not already open for that test.

**Comment by keith-turner** [comment]
Saw this error again when building #987.

```
testTransactorAndCache(org.apache.fluo.integration.impl.TransactorIT)  Time elapsed: 4.763 sec  <<< FAILURE!
java.lang.AssertionError
	at org.apache.fluo.integration.impl.TransactorIT.testTransactorAndCache(TransactorIT.java:67)
```
