### ISSUE TITLE
CollisionIT test failed on Travis

### ISSUE THREAD

**Issue by cjmctague** [apache/incubator-fluo#879]
Travis error for the latest Commit: 4f255a41de2bef60cf38a484b4ce91b3dea2e84f 

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 45.106 sec <<< FAILURE! - in org.apache.fluo.integration.impl.CollisionIT
testLotsOfCollisions(org.apache.fluo.integration.impl.CollisionIT)  Time elapsed: 45.079 sec  <<< FAILURE!
java.lang.AssertionError: Duplicate row col 2:stat:total:2000000000000000
	at org.apache.fluo.integration.impl.CollisionIT.testLotsOfCollisions(CollisionIT.java:167)
```

**Comment by mikewalch** [comment]
I think this is a sporadic test failure as 4f255a41de2bef60cf38a484b4ce91 only contains documentation changes

**Comment by cjmctague** [comment]
Thats what I assumed but was just documenting it

**Comment by keith-turner** [comment]
> Thats what I assumed but was just documenting it

That's the correct thing to do.  Anytime we see a failure unrelated to the PR, we should open an issue.  However, I don't always do this.  I think this is a duplicate of #585.

**Comment by cjmctague** [comment]
```
Running org.apache.fluo.integration.impl.CollisionIT
DEBUG oldestTs : 6839 recentTS : 6839
DEBUG 0 stat:processed [] 6764-WRITE	6755 
DEBUG 0 stat:processed [] 6755-DATA	181
DEBUG 0 stat:total [] 6499-TX_DONE	
DEBUG 0 stat:total [] 6499-WRITE	6472 PRIMARY
DEBUG 0 stat:total [] 6472-DATA	181
DEBUG 1 stat:processed [] 6831-TX_DONE	
DEBUG 1 stat:processed [] 6831-WRITE	6826 PRIMARY
DEBUG 1 stat:processed [] 6826-DATA	223
DEBUG 1 stat:total [] 6821-TX_DONE	
DEBUG 1 stat:total [] 6821-WRITE	6820 PRIMARY
DEBUG 1 stat:total [] 6820-DATA	223
DEBUG 2 stat:processed [] 6681-TX_DONE	
DEBUG 2 stat:processed [] 6681-WRITE	6655 PRIMARY
DEBUG 2 stat:processed [] 6655-DATA	190
DEBUG 2 stat:total [] 6552-TX_DONE	
DEBUG 2 stat:total [] 6552-WRITE	6540 PRIMARY
DEBUG 2 stat:total [] 6540-DATA	190
DEBUG 3 stat:processed [] 6798-WRITE	6797 
DEBUG 3 stat:processed [] 6797-DATA	201
DEBUG 3 stat:total [] 6739-TX_DONE	
DEBUG 3 stat:total [] 6739-WRITE	6707 PRIMARY
DEBUG 3 stat:total [] 6707-DATA	201
DEBUG 4 stat:processed [] 6813-WRITE	6805 
DEBUG 4 stat:processed [] 6805-DATA	205
DEBUG 4 stat:total [] 6792-TX_DONE	
DEBUG 4 stat:total [] 6792-WRITE	6778 PRIMARY
DEBUG 4 stat:total [] 6778-DATA	205
DEBUG all stat:total [] 6831-WRITE	6826 
DEBUG all stat:total [] 140-DEL_LOCK	ABORT PRIMARY 0
DEBUG all stat:total [] 140-DEL_LOCK	ABORT PRIMARY 0
DEBUG all stat:total [] 6826-DATA	1000
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 32.547 sec <<< FAILURE! - in org.apache.fluo.integration.impl.CollisionIT
testLotsOfCollisions(org.apache.fluo.integration.impl.CollisionIT)  Time elapsed: 32.517 sec  <<< FAILURE!
java.lang.AssertionError: Duplicate row col all:stat:total:2000000000000000
	at org.apache.fluo.integration.impl.CollisionIT.testLotsOfCollisions(CollisionIT.java:174)
```
https://travis-ci.org/apache/fluo/jobs/265159869
